### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by sheridanchris** [pimbrouwers/Falco.Htmx#2]
What's the status of this project? Do you plan on publishing this to NuGet? I would love to contribute to getting this project up-to-date and published in any way that I can.

**Comment by dpraimeyuu** [comment]
@sheridanchris well, the status is that it isn't published but along with changes made by @pimbrouwers , it should be usable for the major/most/entire API of `htmx`. So publishing is missing? 😅 

Thanks for reaching out!

**Comment by sheridanchris** [comment]
I would like to submit a PR to add a few missing htmx attributes that were added in recent versions ~~and a build script to publish this.~~

**Comment by AngelMunoz** [comment]
I was just needing this today.
I thought it was already published in NuGet it would be nice to have it published, just my 2 cents 😆

**Comment by pimbrouwers** [comment]
I think it would be great to catch the HTMX wave officially. @dpraimeyuu I am happy to shepherd this repo forward if you aren't able to. Otherwise, I'll remain a casual observer after my initial brain dump haha!

**Comment by dpraimeyuu** [comment]
Thanks for summoning me.

Yeah, you definitely should surf htmx wave!

@AngelMunoz awesome to hear you needed it, but not awesome we're lagging...

...Because of me.

@pimbrouwers let me try to publish it and see how it goes then? :sweat_smile:

**Comment by dpraimeyuu** [comment]
@pimbrouwers @AngelMunoz @sheridanchris @houstonhaynes 
[Falco.Htmx](https://www.nuget.org/packages/Falco.Htmx) :eagle: 

<img src="https://media4.giphy.com/media/VdiQKDAguhDSi37gn1/giphy.gif"/>

The package can be released by publishing a new release on github.

Note: sometimes it's important to get pushed in the positive fashion :-P

**Comment by dpraimeyuu** [comment]
And sorry @sheridanchris that I kept you waiting...

**Comment by pimbrouwers** [comment]
Nice work!
